image: node:lts-alpine

pipelines:
  custom:
    deploy-storybook:
     - step:
         name: Deploy Storybook
         deployment: storybook
         caches:
           - node
         script:
           - apk add openssl
           - yarn global add surge
           - yarn install
           - yarn run storybook:static
           - DOMAIN=$(openssl rand -hex 20).surge.sh
           - surge ./.storybook/static $DOMAIN
  branches:
    master:
      - step:
          name: Deploy Production
          deployment: production
          caches:
            - node
          script:
            - apk add curl
            - /bin/sh .bitbucket/started-deploy.sh P $BITBUCKET_BUILD_NUMBER
            - yarn install
            - yarn run build:production
            - export SPLITTED_FILE=$(basename dist/splitted/main.*.js)
            - export STANDALONE_FILE=$(basename dist/standalone/main.*.js)
            - tar -czvf bundle-p.tar.gz -C dist/ .
            - export HASH=$(sha256sum bundle-p.tar.gz | awk '{print $1;}')
            - mv bundle-p.tar.gz bundle-p.$HASH.tar.gz
            # Upload the file on bitbucket downloads
            - curl -X POST "https://$BB_AUTH@api.bitbucket.org/2.0/repositories/$BITBUCKET_REPO_FULL_NAME/downloads" --form files=@$(echo bundle-p.*.tar.gz)
            # Start request to let conva get the file and put it on the server
            - curl "https://$CONOVA_AUTH@www.blue-tomato.com/deploy-widgets/?file_name=bundle-p.$HASH.tar.gz&file_hash=$HASH"
            - /bin/sh .bitbucket/finished-deploy.sh P $BITBUCKET_BUILD_NUMBER
    develop:
      - step:
          name: Deploy Staging
          deployment: staging
          caches:
            - node
          script:
            - apk add curl
            - /bin/sh .bitbucket/started-deploy.sh Q $BITBUCKET_BUILD_NUMBER
            - yarn install
            - yarn run build:staging
            - export SPLITTED_FILE=$(basename dist/splitted/main.*.js)
            - export STANDALONE_FILE=$(basename dist/standalone/main.*.js)
            - tar -czvf bundle-q.tar.gz -C dist/ .
            - export HASH=$(sha256sum bundle-q.tar.gz | awk '{print $1;}')
            - mv bundle-q.tar.gz bundle-q.$HASH.tar.gz
            # Upload the file on bitbucket downloads
            - curl -X POST "https://$BB_AUTH@api.bitbucket.org/2.0/repositories/$BITBUCKET_REPO_FULL_NAME/downloads" --form files=@$(echo bundle-q.*.tar.gz)
            # Start request to let conva get the file and put it on the server
            - curl "https://$CONOVA_AUTH@qaw.blue-tomato.com/deploy-widgets/?file_name=bundle-q.$HASH.tar.gz&file_hash=$HASH"
            - /bin/sh .bitbucket/finished-deploy.sh Q $BITBUCKET_BUILD_NUMBER
