import React from 'react';
import SnowboardSwap from '.';

export default {
  title: 'Widgets/SnowboardSwap',
};

const data = {
  shops: [
    {
      shopID: 'rosenheim',
      shopName: 'Rosenheim',
      streetName: 'Kufsteiner Straße',
      streetNumber: '14',
      city: 'Rosenheim',
      zip: '83022',
      isocode: 'DE',
      shopEmail: 'rosenheim@blue-tomato.com',
    },
    {
      shopID: 'klagenfurt',
      shopName: 'Klagenfurt',
      streetName: 'Heuplatz',
      streetNumber: '5',
      city: 'Klagenfurt',
      zip: '9020',
      isocode: 'AT',
      shopEmail: 'klagenfurt@blue-tomato.com',
    },
    {
      shopID: 'linz',
      shopName: 'Linz',
      streetName: 'Plus-Kauf-Straße',
      streetNumber: '7',
      city: 'Pasching',
      zip: '4061',
      isocode: 'AT',
      shopEmail: 'linz@blue-tomato.com',
    },
    {
      shopID: 'salzburg',
      shopName: 'Salzburg',
      streetName: 'Waagplatz',
      streetNumber: '1',
      city: 'Salzburg',
      zip: '5020',
      isocode: 'AT',
      shopEmail: 'salzburg@blue-tomato.com',
    },
    {
      shopID: 'wien+scs',
      shopName: 'Vienna SCS',
      streetName: 'SCS Vösendorf Allee',
      streetNumber: '350',
      city: 'Vösendorf',
      zip: '2334',
      isocode: 'AT',
      shopEmail: 'scs@blue-tomato.com',
    },
    {
      shopID: 'essen',
      shopName: 'Essen',
      streetName: 'Limbecker Straße',
      streetNumber: '76',
      city: 'Essen',
      zip: '45127',
      isocode: 'DE',
      shopEmail: 'essen@blue-tomato.com',
    },
    {
      shopID: 'seiersberg',
      shopName: 'Seiersberg',
      streetName: 'ShoppingCity Seiersberg',
      streetNumber: '5',
      city: 'Seiersberg',
      zip: '8054',
      isocode: 'AT',
      shopEmail: 'seiersberg@blue-tomato.com',
    },
    {
      shopID: 'wien+neubaugasse',
      shopName: 'Vienna Neubaugasse',
      streetName: 'Neubaugasse',
      streetNumber: '3',
      city: 'Wien',
      zip: '1070',
      isocode: 'AT',
      shopEmail: 'wien@blue-tomato.com',
    },
    {
      shopID: 'muenchen+city',
      shopName: 'Munich City',
      streetName: 'Oberanger',
      streetNumber: '16',
      city: 'München',
      zip: '80331',
      isocode: 'DE',
      shopEmail: 'muenchen.city@blue-tomato.com',
    },
    {
      shopID: 'genf',
      shopName: 'Geneve',
      streetName: 'Rue De-Grenus',
      streetNumber: '7',
      city: 'Genève',
      zip: '1201',
      isocode: 'CH',
      shopEmail: 'geneve@blue-tomato.com',
    },
    {
      shopID: 'wien+rotenturmstrasse',
      shopName: 'Vienna Rotenturmstrasse',
      streetName: 'Rotenturmstraße',
      streetNumber: '13',
      city: 'Wien',
      zip: '1010',
      isocode: 'AT',
      shopEmail: 'wien1010@blue-tomato.com',
    },
    {
      shopID: 'kempten',
      shopName: 'Kempten',
      streetName: 'Fischerstrasse',
      streetNumber: '22',
      city: 'Kempten',
      zip: '87435',
      isocode: 'DE',
      shopEmail: 'kempten@blue-tomato.com',
    },
    {
      shopID: 'ulm',
      shopName: 'Ulm',
      streetName: 'Münsterplatz',
      streetNumber: '2',
      city: 'Ulm',
      zip: '89073',
      isocode: 'DE',
      shopEmail: 'ulm@blue-tomato.com',
    },
    {
      shopID: 'hamburg+city',
      shopName: 'Hamburg City',
      streetName: 'Ida Ehre Platz',
      streetNumber: '4',
      city: 'Hamburg',
      zip: '20095',
      isocode: 'DE',
      shopEmail: 'hamburg.city@blue-tomato.com',
    },
    {
      shopID: 'schladming',
      shopName: 'Schladming',
      streetName: 'Ritter v. Gersdorffstrasse',
      streetNumber: '562',
      city: 'Schladming',
      zip: '8970',
      isocode: 'AT',
      shopEmail: 'schladming@blue-tomato.com',
    },
    {
      shopID: 'tampere',
      shopName: 'Tampere',
      streetName: 'Hatanpään valtatie',
      streetNumber: '1',
      city: 'Tampere',
      zip: '33100',
      isocode: 'FI',
      shopEmail: 'tampere@blue-tomato.com',
    },
    {
      shopID: 'zuerich+glattzentrum',
      shopName: 'Glatt',
      streetName: 'Neue Winterthurerstrasse',
      streetNumber: '99',
      city: 'Wallisellen',
      zip: '8304',
      isocode: 'CH',
      shopEmail: 'glatt@blue-tomato.com',
    },
    {
      shopID: 'helsinki',
      shopName: 'Helsinki',
      streetName: 'Mannerheimintie',
      streetNumber: '20',
      city: 'Helsinki',
      zip: '00100',
      isocode: 'FI',
      shopEmail: 'helsinki@blue-tomato.com',
    },
    {
      shopID: 'obertauern',
      shopName: 'Obertauern',
      streetName: 'Schützpassage am Pass',
      streetNumber: '',
      city: 'Obertauern',
      zip: '5562',
      isocode: 'AT',
      shopEmail: 'obertauern@blue-tomato.com',
    },
    {
      shopID: 'hannover',
      shopName: 'Hanover',
      streetName: 'Ernst-August-Platz',
      streetNumber: '2',
      city: 'Hannover',
      zip: '30159',
      isocode: 'DE',
      shopEmail: 'hannover@blue-tomato.com',
    },
    {
      shopID: 'koeln',
      shopName: 'Koeln',
      streetName: 'Schildergasse',
      streetNumber: '112',
      city: 'Köln',
      zip: '50667',
      isocode: 'DE',
      shopEmail: 'koeln@blue-tomato.com',
    },
    {
      shopID: 'dresden',
      shopName: 'Dresden',
      streetName: 'Webergasse',
      streetNumber: '1',
      city: 'Dresden',
      zip: '01067',
      isocode: 'DE',
      shopEmail: 'dresden@blue-tomato.com',
    },
    {
      shopID: 'regensburg',
      shopName: 'Regensburg',
      streetName: 'Friedenstraße',
      streetNumber: '23',
      city: 'Regensburg',
      zip: '93053',
      isocode: 'DE',
      shopEmail: 'regensburg@blue-tomato.com',
    },
    {
      shopID: 'hamburg+aez',
      shopName: 'Hamburg AEZ',
      streetName: 'Alstertal-Einkaufszentrum Heegbarg',
      streetNumber: '31',
      city: 'Hamburg',
      zip: '22391',
      isocode: 'DE',
      shopEmail: 'hamburg@blue-tomato.com',
    },
    {
      shopID: 'turku',
      shopName: 'Turku',
      streetName: 'Eerikinkatu',
      streetNumber: '15',
      city: 'Turku',
      zip: '20100',
      isocode: 'FI',
      shopEmail: 'turku@blue-tomato.com',
    },
    {
      shopID: 'garmisch+partenkirchen',
      shopName: 'Garmisch-Partenkirchen',
      streetName: 'Von-Brug-Str.',
      streetNumber: '16-18',
      city: 'Garmisch-Partenkirchen',
      zip: '82467',
      isocode: 'DE',
      shopEmail: 'garmisch@blue-tomato.com',
    },
    {
      shopID: 'karlsruhe',
      shopName: 'Karlsruhe',
      streetName: 'Ettlinger-Tor-Platz',
      streetNumber: '1',
      city: 'Karlsruhe',
      zip: '76133',
      isocode: 'DE',
      shopEmail: 'karlsruhe@blue-tomato.com',
    },
    {
      shopID: 'muenster',
      shopName: 'Muenster',
      streetName: 'Königsstraße',
      streetNumber: '35/36',
      city: 'Münster',
      zip: '48143',
      isocode: 'DE',
      shopEmail: 'muenster@blue-tomato.com',
    },
    {
      shopID: 'passau',
      shopName: 'Passau',
      streetName: 'Bahnhofstraße',
      streetNumber: '1',
      city: 'Passau',
      zip: '94032',
      isocode: 'DE',
      shopEmail: 'passau@blue-tomato.com',
    },
    {
      shopID: 'bonn',
      shopName: 'Bonn',
      streetName: 'Fürstenstraße',
      streetNumber: '4',
      city: 'Bonn',
      zip: '53111',
      isocode: 'DE',
      shopEmail: 'bonn@blue-tomato.com',
    },
    {
      shopID: 'oberhausen',
      shopName: 'Oberhausen',
      streetName: 'Centroallee',
      streetNumber: '145',
      city: 'Oberhausen',
      zip: '46047',
      isocode: 'DE',
      shopEmail: 'oberhausen@blue-tomato.com',
    },
    {
      shopID: 'amsterdam',
      shopName: 'Amsterdam',
      streetName: 'Kalverstraat',
      streetNumber: '193-195',
      city: 'Amsterdam',
      zip: '1012 XC',
      isocode: 'NL',
      shopEmail: 'amsterdam@blue-tomato.com',
    },
    {
      shopID: 'luzern',
      shopName: 'Lucerne',
      streetName: 'Kornmarkt',
      streetNumber: '7',
      city: 'Luzern',
      zip: '6004',
      isocode: 'CH',
      shopEmail: 'luzern@blue-tomato.com',
    },
    {
      shopID: 'freiburg',
      shopName: 'Freiburg',
      streetName: 'Bertoldstraße',
      streetNumber: '7',
      city: 'Freiburg',
      zip: '79098',
      isocode: 'DE',
      shopEmail: 'freiburg@blue-tomato.com',
    },
    {
      shopID: 'villach',
      shopName: 'Villach',
      streetName: 'Kärntner Straße',
      streetNumber: '34',
      city: 'Villach',
      zip: '9500',
      isocode: 'AT',
      shopEmail: 'villach@blue-tomato.com',
    },
    {
      shopID: 'utrecht',
      shopName: 'Utrecht',
      streetName: 'Voor Clarenburg',
      streetNumber: '1-3-5',
      city: 'Utrecht',
      zip: '3511 JE',
      isocode: 'NL',
      shopEmail: 'utrecht@blue-tomato.com',
    },
    {
      shopID: 'stuttgart',
      shopName: 'Stuttgart',
      streetName: 'Alte Poststraße',
      streetNumber: '3',
      city: 'Stuttgart',
      zip: '70173',
      isocode: 'DE',
      shopEmail: 'stuttgart@blue-tomato.com',
    },
    {
      shopID: 'bremen',
      shopName: 'Bremen',
      streetName: 'AG Weser Straße',
      streetNumber: '3',
      city: 'Bremen',
      zip: '28237',
      isocode: 'DE',
      shopEmail: 'bremen@blue-tomato.com',
    },
    {
      shopID: 'bregenz',
      shopName: 'Bregenz',
      streetName: 'Kaiserstraße',
      streetNumber: '32',
      city: 'Bregenz',
      zip: '6900',
      isocode: 'AT',
      shopEmail: 'bregenz@blue-tomato.com',
    },
    {
      shopID: 'winterthur',
      shopName: 'Winterthur',
      streetName: 'Marktgasse',
      streetNumber: '38',
      city: 'Winterthur',
      zip: '8400',
      isocode: 'CH',
      shopEmail: 'winterthur@blue-tomato.com',
    },
    {
      shopID: 'berlin',
      shopName: 'Berlin',
      streetName: 'Nürnberger Straße',
      streetNumber: '13',
      city: 'Berlin',
      zip: '10789',
      isocode: 'DE',
      shopEmail: 'berlin@blue-tomato.com',
    },
    {
      shopID: 'graz',
      shopName: 'Graz',
      streetName: 'Murgasse',
      streetNumber: '11',
      city: 'Graz',
      zip: '8010',
      isocode: 'AT',
      shopEmail: 'graz@blue-tomato.com',
    },
    {
      shopID: 'muenchen',
      shopName: 'Munich',
      streetName: 'Thomas-Wimmer-Ring',
      streetNumber: '14',
      city: 'München',
      zip: '80538',
      isocode: 'DE',
      shopEmail: 'muenchen@blue-tomato.com',
    },
    {
      shopID: 'augsburg',
      shopName: 'Augsburg',
      streetName: 'Bürgermeister-Fischer-Straße',
      streetNumber: '2',
      city: 'Augsburg',
      zip: '86150',
      isocode: 'DE',
      shopEmail: 'augsburg@blue-tomato.com',
    },
    {
      shopID: 'woergl',
      shopName: 'Woergl',
      streetName: 'Bahnhofstraße',
      streetNumber: '54a',
      city: 'Wörgl',
      zip: '6300',
      isocode: 'AT',
      shopEmail: 'woergl@blue-tomato.com',
    },
    {
      shopID: 'alexa',
      shopName: 'Alexa',
      streetName: 'Grunerstraße',
      streetNumber: '20',
      city: 'Berlin',
      zip: '10179',
      isocode: 'DE',
      shopEmail: 'alexa@blue-tomato.com',
    },
    {
      shopID: 'basel',
      shopName: 'Basel',
      streetName: 'Falknerstrasse',
      streetNumber: '7',
      city: 'Basel',
      zip: '4001',
      isocode: 'CH',
      shopEmail: 'basel@blue-tomato.com',
    },
    {
      shopID: 'lienz',
      shopName: 'Lienz',
      streetName: 'Andrä Kranz-Gasse',
      streetNumber: '4',
      city: 'Lienz',
      zip: '9900',
      isocode: 'AT',
      shopEmail: 'lienz@blue-tomato.com',
    },
    {
      shopID: 'shop-detail-lausanne',
      shopName: 'Lausanne',
      streetName: 'Rue St. Laurent',
      streetNumber: '37',
      city: 'Lausanne',
      zip: '1003',
      isocode: 'CH',
      shopEmail: 'lausanne@blue-tomato.com',
    },
    {
      shopID: 'bern',
      shopName: 'Bern',
      streetName: 'Marktgasse',
      streetNumber: '55',
      city: 'Bern',
      zip: '3011',
      isocode: 'CH',
      shopEmail: 'bern@blue-tomato.com',
    },
    {
      shopID: 'zuerich',
      shopName: 'Zurich',
      streetName: 'Limmatquai',
      streetNumber: '122',
      city: 'Zürich',
      zip: '8001',
      isocode: 'CH',
      shopEmail: 'zuerich@blue-tomato.com',
    },
    {
      shopID: 'innsbruck',
      shopName: 'Innsbruck',
      streetName: 'Anichstraße',
      streetNumber: '3',
      city: 'Innsbruck',
      zip: '6020',
      isocode: 'AT',
      shopEmail: 'innsbruck@blue-tomato.com',
    },
    {
      shopID: 'voecklabruck',
      shopName: 'Vöcklabruck',
      streetName: 'Linzer Straße',
      streetNumber: '50',
      city: 'Vöcklabruck',
      zip: '4840',
      isocode: 'AT',
      shopEmail: 'voecklabruck@blue-tomato.com',
    },
    {
      shopID: 'trier',
      shopName: 'Trier',
      streetName: 'Brotstraße',
      streetNumber: '33',
      city: 'Trier',
      zip: '54290',
      isocode: 'DE',
      shopEmail: 'trier@blue-tomato.com',
    },
  ],
  countries: [
    { isocode: 'AT', name: 'Österreich' },
    { isocode: 'DE', name: 'Deutschland' },
    { isocode: 'CH', name: 'Schweiz' },
    { isocode: 'NL', name: 'Niederlande' },
    { isocode: 'FI', name: 'Finnland' },
  ],
  thankYouUrl: '/de-AT/snowboard-swap/thank-you/',
};

export const Default = () => (
  <div>
    <SnowboardSwap data={data} />
  </div>
);
